workflows:
  flutter-ios-workflow:
    name: Flutter iOS Build (IPA Release)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          set -e
          cd ios
          pod install --repo-update

      - name: Build iOS IPA
        script: |
          # --- 核心改动：使用 'flutter build ipa' 命令 ---
          flutter build ipa --release --no-codesign
          
    # --- 关键修复：只保留最重要、最正确的产物路径 ---
    artifacts:
      - build/ios/ipa/*.ipa